# This is the starship configuration file.
# You can customize the appearance of your prompt by modifying this file.
# For more information, see: https://starship.rs/config/

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

#format = "$all"

[line_break]
disabled = true
