#!/bin/bash

if [ -z $WSL_DISTRO_NAME ]; then
    if type clipcopy &>/dev/null; then
        # alias xcp='clipcopy' # for linux (install by apt)
        clipcopy $@
    else
        # alias xcp='xclip -selection clipboard' # for linux (install by apt)
        # this is the default for ubuntu
        xclip -selection clipboard $@
    fi
else
    clip.exe $@
fi
